/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.TravelAgency;
import UserInterface.ManageAirline.ManageAirlinerJPanel;
import java.awt.CardLayout;

/**
 *
 * @author Sumesh
 */
public class TravelAgencyMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMainJFrame
     */
    private TravelAgency travelAgency;
    public TravelAgencyMainJFrame() {
        initComponents();
        this.travelAgency = travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPanel = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        btnTravelAgency = new javax.swing.JButton();
        btnAirliner = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJPanel.setMinimumSize(new java.awt.Dimension(230, 510));
        leftJPanel.setPreferredSize(new java.awt.Dimension(250, 766));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTravelAgency.setText("Travel Agency");
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });
        leftJPanel.add(btnTravelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 50));

        btnAirliner.setText("Airliner");
        btnAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinerActionPerformed(evt);
            }
        });
        leftJPanel.add(btnAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 50));

        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        leftJPanel.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>TRAVEL AGENCY<br/> MANAGEMENT SYSTEM</html>");
        leftJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 110));

        jSplitPanel.setLeftComponent(leftJPanel);

        cardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPanel.setRightComponent(cardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    private void btnAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinerActionPerformed
        // TODO add your handling code here:
        ManageAirlinerJPanel panel = new ManageAirlinerJPanel(cardSequenceJPanel, travelAgency);
        cardSequenceJPanel.add("ManageAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnAirlinerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirliner;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JPanel cardSequenceJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPanel;
    private javax.swing.JPanel leftJPanel;
    // End of variables declaration//GEN-END:variables
}
