/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirline;

import Business.Airliner;
import Business.Flight;
import Business.TravelAgency;
import UserInterface.TravelAgencyWelcome.WelcomeJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumesh
 */
public class ManageAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinerJPanel
     */
    private JPanel cardSequenceJPanel;
    private TravelAgency travelAgency;
    public ManageAirlinerJPanel(JPanel cardSequenceJPanel, TravelAgency travelAgency) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.travelAgency = travelAgency;
        calculateNumberOfArplanes();
        populateAirlinersTable();
        btnClearSearch.setEnabled(false);
    }
    
    public void populateAirlinersTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblMngAirline.getModel();
        dtm.setRowCount(0);
        for(Airliner airliner: travelAgency.getAirlinerDirectory().getAirlinerList()) {
            Object[] row = new Object[2];
            row[0]=airliner;
            row[1]=airliner.getAirlinerNoOfAirplanes();                        
            dtm.addRow(row);
        }
    }
    
    private void calculateNumberOfArplanes(){
    
        int count = 0;
        for(Airliner airliner: travelAgency.getAirlinerDirectory().getAirlinerList()){
            for(Flight flight:airliner.getFlightList()){
                if(airliner.getAirlinerName().equals(flight.getAirlinerName())){
                    count++;
                }
            }
            airliner.setAirlinerNoOfAirplanes(count);
            count = 0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMngAirline = new javax.swing.JTable();
        btnAddAirliner = new javax.swing.JButton();
        btnViewAirliner = new javax.swing.JButton();
        btnDeleteAirliner = new javax.swing.JButton();
        txtSearchAirliner = new javax.swing.JTextField();
        btnSearchAirliner = new javax.swing.JButton();
        btnClearSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Airliner");

        tblMngAirline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblMngAirline.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        tblMngAirline.setForeground(new java.awt.Color(153, 0, 0));
        tblMngAirline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Names", "Number of Airplanes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMngAirline.setGridColor(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(tblMngAirline);
        if (tblMngAirline.getColumnModel().getColumnCount() > 0) {
            tblMngAirline.getColumnModel().getColumn(0).setResizable(false);
            tblMngAirline.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAddAirliner.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnAddAirliner.setForeground(new java.awt.Color(153, 0, 0));
        btnAddAirliner.setText("Add New Airliner");
        btnAddAirliner.setBorder(null);
        btnAddAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirlinerActionPerformed(evt);
            }
        });

        btnViewAirliner.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnViewAirliner.setForeground(new java.awt.Color(153, 0, 0));
        btnViewAirliner.setText("View Airliner Details");
        btnViewAirliner.setBorder(null);
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnDeleteAirliner.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnDeleteAirliner.setForeground(new java.awt.Color(153, 0, 0));
        btnDeleteAirliner.setText("Delete Airliner");
        btnDeleteAirliner.setBorder(null);
        btnDeleteAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlinerActionPerformed(evt);
            }
        });

        btnSearchAirliner.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnSearchAirliner.setForeground(new java.awt.Color(153, 0, 0));
        btnSearchAirliner.setText("Search");
        btnSearchAirliner.setBorder(null);
        btnSearchAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAirlinerActionPerformed(evt);
            }
        });

        btnClearSearch.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnClearSearch.setForeground(new java.awt.Color(153, 0, 0));
        btnClearSearch.setText("Clear Search");
        btnClearSearch.setBorder(null);
        btnClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAddAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(85, 85, 85)
                                    .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnSearchAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirlinerActionPerformed
        // TODO add your handling code here:
        CreateAirlinerJPanel panel = new CreateAirlinerJPanel(cardSequenceJPanel, travelAgency);
        cardSequenceJPanel.add("CreateAirlinerJPanel",panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);        
    }//GEN-LAST:event_btnAddAirlinerActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        int slectedRow = tblMngAirline.getSelectedRow();
        if(slectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select row to view flight details!!");
        }
        else{
        Airliner airliner = (Airliner)tblMngAirline.getValueAt(slectedRow,0);
           ViewAirlinerDetailsJPanel panel = new ViewAirlinerDetailsJPanel(cardSequenceJPanel,airliner);
           cardSequenceJPanel.add("ViewAirlinerDetailsJPanel",panel);
           CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
           layout.next(cardSequenceJPanel);
        }
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnDeleteAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlinerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMngAirline.getSelectedRow();
        if(selectedRow  >= 0) {
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the airliner details ?","Warning",dialogButton);
           if(dialogResult == JOptionPane.YES_OPTION) {
               Airliner airliner = (Airliner)tblMngAirline.getValueAt(selectedRow,0);
               travelAgency.getAirlinerDirectory().deleteAirliner(airliner);
               populateAirlinersTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteAirlinerActionPerformed

    private void btnSearchAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAirlinerActionPerformed
        // TODO add your handling code here:
        btnClearSearch.setEnabled(true);
        btnSearchAirliner.setEnabled(false);
        String searchText = txtSearchAirliner.getText();
        if(searchText.equals("") || searchText == null){
            JOptionPane.showMessageDialog(null, "Please enter Airliner name to search");
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel) tblMngAirline.getModel();
            dtm.setRowCount(0);
            for(Airliner airliner: travelAgency.getAirlinerDirectory().getAirlinerList()) {
            if(airliner.getAirlinerName().equalsIgnoreCase(searchText)){
                Object[] row = new Object[2];
                row[0]=airliner;
                row[1]=airliner.getAirlinerNoOfAirplanes();

                dtm.addRow(row);
            }
          }
        }
    }//GEN-LAST:event_btnSearchAirlinerActionPerformed

    private void btnClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSearchActionPerformed
        // TODO add your handling code here:
        populateAirlinersTable();
        btnClearSearch.setEnabled(false);
        btnSearchAirliner.setEnabled(true);
        txtSearchAirliner.setText("");
    }//GEN-LAST:event_btnClearSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirliner;
    private javax.swing.JButton btnClearSearch;
    private javax.swing.JButton btnDeleteAirliner;
    private javax.swing.JButton btnSearchAirliner;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblMngAirline;
    private javax.swing.JTextField txtSearchAirliner;
    // End of variables declaration//GEN-END:variables
}
