/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.CardLayout;
import Business.TravelAgency;

/**
 *
 * @author Sumesh
 */
public class TravelAgencyMain extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMain
     */
    private TravelAgency travelAgency;
    public TravelAgencyMain() {
        initComponents();
        this.travelAgency = new TravelAgency();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTravelAgency = new javax.swing.JButton();
        btnAirliners = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        cardSequenceJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJPanel.setMinimumSize(new java.awt.Dimension(230, 510));
        leftJPanel.setPreferredSize(new java.awt.Dimension(230, 776));
        leftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>TRAVEL AGENCY<br/> MANAGEMENT SYSTEM</html>");
        leftJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        btnTravelAgency.setBackground(new java.awt.Color(245, 245, 246));
        btnTravelAgency.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnTravelAgency.setForeground(new java.awt.Color(78, 114, 175));
        btnTravelAgency.setText("Travel Agency");
        btnTravelAgency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });
        leftJPanel.add(btnTravelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 50));

        btnAirliners.setBackground(new java.awt.Color(245, 245, 246));
        btnAirliners.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAirliners.setForeground(new java.awt.Color(78, 114, 175));
        btnAirliners.setText("Airliners");
        btnAirliners.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinersActionPerformed(evt);
            }
        });
        leftJPanel.add(btnAirliners, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 50));

        btnCustomers.setBackground(new java.awt.Color(245, 245, 246));
        btnCustomers.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(78, 114, 175));
        btnCustomers.setText("Customers");
        btnCustomers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        leftJPanel.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 50));

        jSplitPane2.setLeftComponent(leftJPanel);

        cardSequenceJPanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(cardSequenceJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        // TODO add your handling code here:
//        TravelAgencyMngWorkAreaJPanel panel = new TravelAgencyMngWorkAreaJPanel(cardSequenceJPanel,travelAgency);
//        cardSequenceJPanel.add("TravelAgencyMngWorkAreaJPanel", panel);
//        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
//        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    private void btnAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinersActionPerformed
        // TODO add your handling code here:
//        AirlinersMngWorkAreaJPanel panel = new AirlinersMngWorkAreaJPanel(cardSequenceJPanel,travelAgency);
//        cardSequenceJPanel.add("AirlinersMngWorkAreaJPanel", panel);
//        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
//        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnAirlinersActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        //TODO add your handling code here:
//        CustomersMngWorkAreaJPanel panel = new CustomersMngWorkAreaJPanel(cardSequenceJPanel,travelAgency);
//        cardSequenceJPanel.add("CustomersMngWorkAreaJPanel",panel);
//        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
//        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnCustomersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirliners;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.JPanel cardSequenceJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel leftJPanel;
    // End of variables declaration//GEN-END:variables
}
