/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAdmin;

import Business.Abstract.Admin;
import Business.TravelAgency;
import UserInterface.ManageAirline.ManageAirlinerJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sumesh
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    List<Admin> list;
    private TravelAgency travelAgency;
    private JPanel cardSequenceJPanel;    
    public LoginJPanel( TravelAgency travelAgency, JPanel cardSequenceJPanel) {
        initComponents();
        this.travelAgency = travelAgency;
        this.list = travelAgency.getAdminDir().getAdminList();
        this.cardSequenceJPanel = cardSequenceJPanel;
        AdminUsername();
    }

    public void AdminUsername(){
        comboAdmin.removeAllItems();
        for(Admin u:list){
            
            comboAdmin.addItem(u.getUserName());
             
        }       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboAdmin = new javax.swing.JComboBox<>();
        txtPasswordAdmin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnLoginAdmin = new javax.swing.JButton();
        btnCreateAdminUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Travel Admin Login");

        txtPasswordAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        btnLoginAdmin.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnLoginAdmin.setForeground(new java.awt.Color(153, 0, 0));
        btnLoginAdmin.setText("Login");
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });

        btnCreateAdminUser.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnCreateAdminUser.setForeground(new java.awt.Color(153, 0, 0));
        btnCreateAdminUser.setText("Create Admin User");
        btnCreateAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboAdmin, 0, 164, Short.MAX_VALUE)
                            .addComponent(txtPasswordAdmin))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateAdminUser)
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(btnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCreateAdminUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(comboAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        // TODO add your handling code here:
        String uName = (String) comboAdmin.getSelectedItem();
        String password = txtPasswordAdmin.getText();
        if(password == null || password == ""){
            JOptionPane.showMessageDialog(null, "Please enter passowrd!!");
        }else {            
            for(Admin admin : travelAgency.getAdminDir().getAdminList()){
                if(admin.getUserName().equals(uName)){
                    if(admin.verify(password)){
                        ManageAirlinerJPanel panel = new ManageAirlinerJPanel(cardSequenceJPanel, travelAgency);
                        cardSequenceJPanel.add("ManageAirlinerJPanel", panel);
                        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
                        layout.next(cardSequenceJPanel);
                    }else{
                        JOptionPane.showMessageDialog(null, "Please enter correct password!!");
                    }
                }
            }
            
        }
       
    }//GEN-LAST:event_btnLoginAdminActionPerformed

    private void btnCreateAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminUserActionPerformed
        // TODO add your handling code here:
        AdminCreateJPanel panel = new AdminCreateJPanel(cardSequenceJPanel, travelAgency);
        cardSequenceJPanel.add("AdminCreateJPanel", panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnCreateAdminUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAdminUser;
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JComboBox<String> comboAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtPasswordAdmin;
    // End of variables declaration//GEN-END:variables
}
